FROM kartoza/geoserver:2.24.1

# Puerto por defecto en Kartoza GeoServer
EXPOSE 8080

# Puedes agregar configuraciones adicionales o copiar directorios de datos si los tienes
# COPY ./data_dir /opt/geoserver/data_dir
